### ISSUE TITLE
alisanli: wrong subject

### ISSUE THREAD

**Issue by alisanlii** [HYF-Class21/workflows-group3-intro#7]
#We need to change our files!
Hi team! We have to change our contents from country to our infos.

**Comment by samirm00** [comment]
Hello @alisanlii What do you mean by `wrong subject` ? why this issue is still opens ?

**Comment by alisanlii** [comment]
> Hello @alisanlii What do you mean by `wrong subject` ? why this issue is still opens ?

Hi @samirm00 I have explained below.

**Comment by samirm00** [comment]
@alisanlii  I know, but the issue title is not clear at all, that is what I meant.
